public class Calculator {
    
   /* integer x=10;
    integer y=90;*/
    integer z;
    Public integer Addition(integer x, integer y)
    { 
     
     return z=x+y;
        
    // system.debug('The value of z is'+z);
    }
    Public integer Subtraction(integer x, integer y)
    { 
     
     return z=x-y;
    }   
    
    Public integer Multiplication(integer x, integer y)
    { 
    
     return z=x*y;
    }
    
    Public integer Division(integer x, integer y)
    { 
    
     return z=x/y;
    }
}