public class CompareValues {
    
    /*Integer x;
    Integer y;
    
   Public String compare(x, y) // error while stating like this - ask trainer*/

    Public String z;
    
    Public String compare(integer x, integer y)
    {
        if (x>y)
        {
            system.debug(z= 'X is greater than Y');
        }
            else
            {
             system.debug(z= 'Y is greater than X');   
            }
       
        return z;
    }
    
}