public class Course {

   public String courseType, courseName, courseDuration;
   public Decimal courseFee;
    
    public course(String courseType, String courseName, 
                  String courseDuration, Decimal courseFee)
       
  		{
           this.courseType = courseType; 
           this.courseName = courseName;
           this.courseDuration = CourseDuration; 
           this.courseFee = courseFee;
                     
         }         
}